# Generated by Django 3.2.8 on 2022-02-23 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0005_auto_20220223_1501'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(default=' ', max_length=50)),
                ('allocation_percentage', models.IntegerField(default=' ')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('comments', models.CharField(default=' ', max_length=50)),
                ('Project_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project_name', models.ForeignKey(default=' ', max_length=50, on_delete=django.db.models.deletion.DO_NOTHING, related_name='client', to='manager.project')),
            ],
        ),
    ]
