# Generated by Django 4.0.4 on 2022-04-16 07:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_alter_client_id_alter_employee_id_alter_project_id'),
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='Email',
            field=models.EmailField(default='example@gmail.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='employee_name',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, related_name='name', to='manager.employee'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='end_date',
            field=models.DateField(default=datetime.date(9999, 12, 31)),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='start_date',
            field=models.DateField(default=datetime.date(1, 1, 1)),
        ),
    ]
