# Generated by Django 4.0.4 on 2022-04-18 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_alter_client_id_alter_employee_id_alter_project_id'),
        ('assignment', '0003_rename_email_assignment_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='end_date',
            field=models.DateField(default=' '),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='project_name',
            field=models.ForeignKey(default=' ', max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='manager.project'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='start_date',
            field=models.DateField(default=' '),
        ),
    ]
